### ISSUE TITLE
Impossible to create thin outline?

### ISSUE THREAD

**Issue by Kagami** [apocalyptech/gimp-text-outline#2]
Hi. Thank you for such great plugin.

It seems to be unstable on gimp 2.9 though. I'm trying to create thin outline for text with font size=30 and brush size=1 and instead it gives me this:

![g-o](https://cloud.githubusercontent.com/assets/533383/13527102/c5a84ec0-e21d-11e5-80df-49d2ee91db11.png)

Probably I'm missing something, I was able to create thin outline several times but I'm not sure whether sequence of actions was different.

I also get the following error in console:

```
(gimp:9313): Gimp-Core-CRITICAL **: gimp_stroke_options_prepare: assertion 'paint_info == paint_options->paint_info' failed

(gimp:9313): Gimp-Paint-CRITICAL **: gimp_paint_core_stroke_vectors: assertion 'GIMP_IS_PAINT_OPTIONS (paint_options)' failed
Traceback (most recent call last):
  File "/usr/lib64/gimp/2.0/python/gimpfu.py", line 851, in _run
    res = apply(func, params[1:])
  File "/home/kagami/.config/GIMP/2.9/plug-ins/text-outline.py", line 94, in add_text_outline
    stroke_path_and_remove(image, new_layer, path)
  File "/home/kagami/.config/GIMP/2.9/plug-ins/text-outline.py", line 67, in stroke_path_and_remove
    pdb.gimp_edit_stroke_vectors(layer, path)
RuntimeError: execution error
```

Especially if I execute Text Outline filter with Brush/Pencil tool active. But sometimes it works that way too.

**Comment by apocalyptech** [comment]
Hmm, I know that it's been four months, but I'll see if I can figure out what's up with this (and if it's still happening after all this time).

**Comment by Musaran2** [comment]
GIMP is not designed for "pixel art", so using selection vs path an/or pencil vs brush may either straddle the pixel boundary or pixel middle, leading to inconsistent results.

On thin strokes, it shows.

As of v2.10.14 this works for me on very thin lines :

### The selection way 
1. Text context menu>"_Alpha to Selection_"
1. "_Select>Invert_" (to avoid painting over the text).
1. Create or select underlying layer.
Optional, but better for later rework as it leaves text untouched an allows different outline blending.
1. "_Edit>Stroke Selection..._" then either of...
- - a) "_Stroke line_", "_Solid_", "_Antialiasing_", "_Line width_" = intended outline width×2-1 .
The -1 (or anything ]0,-2[ in fact) anti-aliases the outermost pixel border. This makes a 1-2px outline sufficiently smooth.
**Caveat**: The rest of the outline is squarish and solid fill.
- - b) "_Stroke with a paint tool_", after setting the tool "_Size_" to intended outline width×2.
**Caveat 1**: Shifts half a pixel to the bottom right. (very noticeable under a few pixels of width)
**Caveat 2**: Tight spaces may get painted twice, this can be bad for transparency.

### The path alternative
1. "_Text to Path_" instead of selection.
2. Nothing.
3. Mandatory, unless painting over the text is ok.
4. "Stroke Path..." instead of "Stroke Selection..."

### Don'ts
- Select pixels then "_Select>To path_".
It cuts and rounds through pixel corners, ending inside the original text and significantly off-shape for small text.
- "_Antilasing_" text, as it mixes badly with the outline.
Moreover selection might fail as the conversion above.
- Text context menu>_"Text to Path_" then "_Select>From Path_".
It misses some text pixels.

**Comment by 0lm** [comment]
As in 2.10.24, you just double click on the Text layer and run this filter. Everything works fine and you can set the outline as thin as you want. No selection hacks and tricks are needed anymore. Just select text layer in 2.10.24 and run the filter, thats all you need to do. (I can confirm this, since I tested it)
Also have in mind to put this addon into "plug-ins" and not into "scripts". There are some addons needing to put into scripts, and others into plug-ins.

**Comment by Kagami** [comment]
Thanks, I will try it.
